import type { SketchInfo } from "../types/SketchInfo";
import RotatingSquaresDashboard from "../components/controls/rotating-squares";
import { getSketchSourceUrl } from "../utils/get-sketch-source";

export const SKETCH_CATALOG_INFO: SketchInfo[] = [
  {
    path: "pine-tree",
    title: "Pine Tree",
    loadSketch: () => import("../sketches/pineTree.ts"),
    githubUrl: getSketchSourceUrl("pineTree"),
  },
  {
    path: "flow-field",
    title: "Flow Field",
    loadSketch: () => import("../sketches/flowField.ts"),
    githubUrl: getSketchSourceUrl("flowField"),
  },
  {
    path: "rotating-squares",
    title: "Rotating Squares",
    dashboard: RotatingSquaresDashboard,
    loadSketch: () => import("../sketches/rotatingSquares.ts"),
    githubUrl: getSketchSourceUrl("rotatingSquares"),
  },
  {
    path: "bouncing-lines",
    title: "Bouncing Lines",
    loadSketch: () => import("../sketches/bouncingLines.ts"),
    githubUrl: getSketchSourceUrl("bouncingLines"),
  },
  {
    path: "bouncing-circles",
    title: "Bouncing Circles",
    loadSketch: () => import("../sketches/bouncingCircles.ts"),
    githubUrl: getSketchSourceUrl("bouncingCircles"),
  },
  {
    path: "circles-around-circles",
    title: "Circles Around Circles",
    loadSketch: () => import("../sketches/circlesAroundCircles.ts"),
    githubUrl: getSketchSourceUrl("circlesAroundCircles"),
  },
  {
    path: "connected-dots",
    title: "Connected Dots",
    loadSketch: () => import("../sketches/connectedDots.ts"),
    githubUrl: getSketchSourceUrl("connectedDots"),
  },
  {
    path: "cow-effect",
    title: "Cow Effect",
    loadSketch: () => import("../sketches/cowEffect.ts"),
    githubUrl: getSketchSourceUrl("cowEffect"),
  },
  {
    path: "insertion-sort",
    title: "Insertion Sort",
    loadSketch: () => import("../sketches/insertionSort.ts"),
    githubUrl: getSketchSourceUrl("insertionSort"),
  },
  {
    path: "kaleidoscope",
    title: "Kaleidoscope",
    loadSketch: () => import("../sketches/kaleidoscope.ts"),
    githubUrl: getSketchSourceUrl("kaleidoscope"),
  },
  {
    path: "manual-clock",
    title: "Manual Clock",
    loadSketch: () => import("../sketches/manualClock.ts"),
    githubUrl: getSketchSourceUrl("manualClock"),
  },
  {
    path: "matrix-digital-rain",
    title: "Matrix Digital Rain",
    loadSketch: () => import("../sketches/matrixDigitalRain.ts"),
    githubUrl: getSketchSourceUrl("matrixDigitalRain"),
  },
  {
    path: "trippy-effect",
    title: "Trippy Effect",
    loadSketch: () => import("../sketches/trippyEffect.ts"),
    githubUrl: getSketchSourceUrl("trippyEffect"),
  },
  {
    path: "sync-by-sin",
    title: "Sync By Sin",
    loadSketch: () => import("../sketches/syncBySin.ts"),
    githubUrl: getSketchSourceUrl("syncBySin"),
  },
  {
    path: "spirograph",
    title: "Spirograph",
    loadSketch: () => import("../sketches/spirograph.ts"),
    githubUrl: getSketchSourceUrl("spirograph"),
  },
  {
    path: "spiral-rgb",
    title: "Spiral RGB",
    loadSketch: () => import("../sketches/spiralRGB.ts"),
    githubUrl: getSketchSourceUrl("spiralRGB"),
  },
  {
    path: "sin-visualization",
    title: "Sin Visualization",
    loadSketch: () => import("../sketches/sinVisualization.ts"),
    githubUrl: getSketchSourceUrl("sinVisualization"),
  },
  {
    path: "sin-cos-waves",
    title: "Sin-Cos Waves",
    loadSketch: () => import("../sketches/sinCosWaves.ts"),
    githubUrl: getSketchSourceUrl("sinCosWaves"),
  },
  {
    path: "rotate-and-align",
    title: "Rotate And Align",
    loadSketch: () => import("../sketches/rotateAndAlign.ts"),
    githubUrl: getSketchSourceUrl("rotateAndAlign"),
  },
  {
    path: "recursive-trees",
    title: "Recursive Trees",
    loadSketch: () => import("../sketches/recursiveTrees.ts"),
    githubUrl: getSketchSourceUrl("recursiveTrees"),
  },
  {
    path: "random-tree",
    title: "Random Tree",
    loadSketch: () => import("../sketches/randomTree.ts"),
    githubUrl: getSketchSourceUrl("randomTree"),
  },
  {
    path: "random-topographic-maps",
    title: "Random Topographic Maps",
    loadSketch: () => import("../sketches/randomTopographicMaps.ts"),
    githubUrl: getSketchSourceUrl("randomTopographicMaps"),
  },
  {
    path: "rainbow-flower",
    title: "Rainbow Flower",
    loadSketch: () => import("../sketches/rainbowFlower.ts"),
    githubUrl: getSketchSourceUrl("rainbowFlower"),
  },
  {
    path: "perlin-noise-waves",
    title: "Perlin Noise Waves",
    loadSketch: () => import("../sketches/perlinNoiseWaves.ts"),
    githubUrl: getSketchSourceUrl("perlinNoiseWaves"),
  },
  {
    path: "optical-illusion-circles",
    title: "Optical Illusion Circles",
    loadSketch: () => import("../sketches/opticalIllusionCircles.ts"),
    githubUrl: getSketchSourceUrl("opticalIllusionCircles"),
  },
  {
    path: "animated-topgraphic-maps",
    title: "Animated Topographic Maps",
    loadSketch: () => import("../sketches/animatedTopographicMaps.ts"),
    githubUrl: getSketchSourceUrl("animatedTopographicMaps"),
  },
  {
    path: "mirror-draw",
    title: "Mirror Draw",
    loadSketch: () => import("../sketches/mirrorDraw.ts"),
    githubUrl: getSketchSourceUrl("mirrorDraw"),
  },
  {
    path: "pendulum-waves",
    title: "Pendulum Waves",
    loadSketch: () => import("../sketches/pendulumWaves.ts"),
    githubUrl: getSketchSourceUrl("pendulumWaves"),
  },
  {
    path: "sand-effect",
    title: "Sand Effect",
    loadSketch: () => import("../sketches/sandEffect.ts"),
    githubUrl: getSketchSourceUrl("sandEffect"),
  },
  // {
  //   path: "rings-draw",
  //   title: "Rings Draw",
  //   loadSketch: () => import("../sketches/ringsDraw.ts"),
  //   githubUrl: getSketchSourceUrl("ringsDraw"),
  // },
  {
    path: "rotating-circles",
    title: "Rotating Circles",
    loadSketch: () => import("../sketches/rotatingCircles.ts"),
    githubUrl: getSketchSourceUrl("rotatingCircles"),
  },
  {
    path: "circle-loop",
    title: "Circle Loop",
    loadSketch: () => import("../sketches/circleLoop.ts"),
    githubUrl: getSketchSourceUrl("circleLoop"),
  },
  {
    path: "perlin-noise-rays",
    title: "Perlin Noise Rays",
    loadSketch: () => import("../sketches/perlinNoiseRays.ts"),
    githubUrl: getSketchSourceUrl("perlinNoiseRays"),
  },
  {
    path: "animated-flow-field",
    title: "Animated Flow Field",
    loadSketch: () => import("../sketches/animatedFlowField.ts"),
    githubUrl: getSketchSourceUrl("animatedFlowField"),
  },
];
