export const SKETCH_FILES = [
  "rotating-squares",
  "spirograph",
  "spiral-rgb",
  "rotate-and-align",
  "perlin-noise-waves",
  "pendulum-waves",
  "optical-illusion-circles",
  "mirror-draw",
  "kaleidoscope",
  "cow-effect",
  "circles-around-circles",
  "circle-loop",
  "bouncing-lines",
  "bouncing-circles",
  "animated-topographic-maps",
  "animated-flow-field",
  "sand-effect",
  "sin-cos-waves",
  "sin-visualization",
  "rainbow-flower",
  "trippy-effect",
  "connected-dots",
  "rotating-circles",
  // "aim-trainer",
  // "perlin-noise-rays",
  // "fireworks",
  // "perlin-noise-tree",
  // "animated-topographic-maps",
  // "flow-field",
  // "bouncing-circles",
  // "insertion-sort",
  // "pine-tree",
  // "camera-effects",
  // "manual-clock",
  // "random-topographic-maps",
  // "camera-effects2",
  // "matrix-digital-rain",
  // "random-tree",
  // "sync-by-sin",
  // "christmas-tree",
  // "microphone-visualizer",
  // "recursive-trees",
  // "rings-draw",
] as const;
